=== alapierre/from_svn/commons-dictionary/src/main/xsd/administrative-division.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Adrian (SoftProject) -->
<!-- author Adrian Lapierre-MrÃ³z (www.soft-project.pl) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.softproject.com.pl/commons-administrative-division" targetNamespace="http://www.softproject.com.pl/commons-administrative-division">
	<xs:element name="administrative-division">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="province" type="ns1:Province" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="last-updated" type="xs:dateTime" default="2011-12-01T00:00:00"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="CommunityType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="powiat-grodzki"/>
			<xs:enumeration value="miejska"/>
			<xs:enumeration value="wiejska"/>
			<xs:enumeration value="miejsko-wiejska"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Province">
		<xs:sequence>
			<xs:element name="district" type="ns1:District" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="District">
		<xs:sequence>
			<xs:element name="community" type="ns1:Community" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Community">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="teryc" type="xs:string" use="required"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="ns1:CommunityType"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== alapierre/from_svn/commons-dictionary/src/test/resources/gminy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<n:administrative-division xmlns:n="http://www.softproject.com.pl/commons-administrative-division" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.softproject.com.pl/commons-administrative-division
http://schema.softproject.com.pl/commons-dictionary/administrative-division.xsd">
	<province name="Mazowieckie">
		<district name="Warszawski Zachodni">
			<community name="Łomianki" teryc="143205" type="miejsko-wiejska"/>
			<community name="Błonie" teryc="143201" type="miejsko-wiejska"/>
			<community name="Izabelin" teryc="143202" type="wiejska"/>
			<community name="Kampinos" teryc="143203" type="wiejska"/>
			<community name="Leszno" teryc="143204" type="wiejska"/>
			<community name="Ożarów Mazowiecki" teryc="143206" type="miejsko-wiejska"/>
			<community name="Stare Babice" teryc="143207" type="wiejska"/>
		</district>
		<district name="Sokołowski">
			<community name="Sokołów Podlaski" teryc="142901" type="miejska"/>
			<community name="Bielany" teryc="142902" type="wiejska"/>
			<community name="Ceranów" teryc="142903" type="wiejska"/>
			<community name="Jabłonna Lacka" teryc="142904" type="wiejska"/>
			<community name="Kosów Lacki" teryc="142905" type="miejsko-wiejska"/>
			<community name="Repki" teryc="142906" type="wiejska"/>
			<community name="Sabnie" teryc="142907" type="wiejska"/>
			<community name="Sokołów Podlaski" teryc="142908" type="wiejska"/>
			<community name="Sterdyń" teryc="142909" type="wiejska"/>
		</district>		
	</province>
	<province name="Podkarpackie">
		<district name="Bieszczadzki">
			<community name="Czarna" teryc="180103" type="wiejska"/>
			<community name="Lutowiska" teryc="180105" type="wiejska"/>
			<community name="Ustrzyki Dolne" teryc="180108" type="miejsko-wiejska"/>
		</district>
		<district name="m. Rzeszów">
			<community name="M. Rzeszów" type="powiat-grodzki" teryc="186301"/>
		</district>
	</province>
</n:administrative-division>
